apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-es-config
data:
  forward.input.conf: |-
    # Takes the messages sent over TCP
    <source>
      type tail
      path /data/logs/access_log 
      #pos_file /var/log/td-agent/apache-access.log.pos
      tag apache.access
      format apache2
    </source>
  output.conf: |-
    <match **>
       type elasticsearch
       log_level info
       include_tag_key true
       host es
       port 9200
       logstash_format true
       index_name fluentd-apache-access
       # Set the chunk limits.
       buffer_chunk_limit 2M
       buffer_queue_limit 8
       flush_interval 5s
       # Never wait longer than 5 minutes between retries.
       max_retry_wait 30
       # Disable the limit on the number of retries (retry forever).
       disable_retry_limit
       # Use multiple threads for processing.
       num_threads 2
    </match>
