apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluentd-es
  labels:
    app: fluentd-es
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  template:
    metadata:
      labels:
        app: fluentd-es
    spec:
      nodeSelector:
        kubernetes.io/hostname: kworker-1
      containers:
      - name: fluentd-es
        image: gcr.io/google-containers/fluentd-elasticsearch:v2.0.1
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q
        resources:
          limits:
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/fluent/config.d
        - name: apache-log
          mountPath: /data/logs
          subPath: logs
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-volume
        configMap:
          name: fluentd-es-config
      - name: apache-log
        persistentVolumeClaim:
          claimName: pvc0001 
